### ISSUE TITLE
Изменить неудачные названия

### ISSUE THREAD

**Issue by WoWaster** [FormalLanguageConstrainedPathQuerying/formal-lang-course#122]
Некоторые названия функций и классов получились не очень. Все пункты скорее всего требуют обсуждения.
* `FiniteAutomaton` клэшится с оным в pyformlang, предлагаю `MatrixFA` (ещё есть мысль просить не конструкторы, а статические методы типа `from_pyformlang`, иначе там какая-то дичь в конструкторе вылезает)
* `project -> flc` (formal lang course) 
* `paths_ends -> ???`
* `reachability_with_constraints -> ???`
* `TestReachability` -> `TestRPQ` & `TestCFPQ`

Список будет пополняться

**Comment by gsvgit** [comment]
Для реализуемых функций тоже надо подумать.
```paths_ends``` и прочее - что-то странное. Оно же всё про разные варианты ```RPQ```: ```tensor_based_rpq```, ```ms_bfs_based_rpq``` и т.д.

**Comment by WoWaster** [comment]
Ага, об этом тоже надо подумать, не успел спросить как лучше их назвать
