### ISSUE TITLE
Добавить гарантированно содержательные тесты

### ISSUE THREAD

**Issue by WoWaster** [FormalLanguageConstrainedPathQuerying/formal-lang-course#135]
С текущим генератором графов для RPQ и CFPQ легко нарваться на ответы типа `[set(), set(), set(), set()]` в большой части тестов. Это может привести к адекватным на первый взгляд решениям, которые на самом деле некорректны.
Эту проблему можно попробовать решить двумя путями:
1. *Curated* набор тестов. Буквально по одному-двум на задачку, с гарантировано не пустым ответом.
2. Попробовать использовать генератор более плотных графов. Можно в комбинации.

**Comment by gsvgit** [comment]
Накидал в [документе](https://www.overleaf.com/project/65c5df6752ad42fde98415aa).
