### ISSUE TITLE
Задание 13, типизация `Get_start` для `RSM`

### ISSUE THREAD

**Issue by TimPushkin** [FormalLanguageConstrainedPathQuerying/formal-lang-course#61]
Сейчас типизация `Get_start` для `RSM` описывается так:
```
[e](b) => RSM<t>
____________________________
[Get_start (e)](b) => RSM<t>
```

Это опечатка (кажется, что снизу должно быть `[Get_start (e)](b) => Set<t>`) или поразумевается не просто возврат вершин, а что-то другое (например, также возврат информации о том, для какого нетерминала каждая вершина является стартовой, но тогда все равно не ясно, почему именно `RSM<t>`)?

**Comment by TimPushkin** [comment]
Вообще по описанной системе типов не понятно, откуда должен изначально взяться `RSM`: загрузить можно только `FA`, а все доступные операции над ними замкнуты

**Comment by gsvgit** [comment]
@TimPushkin 
1. Да, это опечатка. Там действительно множество. Испавлено. 
2. Про то, откуда возьмутся RSM мы обсуждали, что это как раз момент творчества: так как по запросу (грамматике) не всегда можно опнять, задаёт ли она регулярный язык, то придётся что-то изобрести, чтобы в нужный момент сказать "Вот теперь всё. Это может не быть регуляркой." Например, при рекурсивных запросах. Так что да. Там, на самом деле, специально не все правила аккуратно выписаны.

**Comment by TimPushkin** [comment]
Понятно, спасибо
