### ISSUE TITLE
Дайте записи видео лекций!

### ISSUE THREAD

**Issue by likern** [FormalLanguageConstrainedPathQuerying/formal-lang-course#85]
Братишки, родненькие! 🥺  Поделитесь видеолекциями курса, пожалуйста! Хочу написать парсер SQL, не хватает формальных знаний.

Ваши записи (не читал, но пробежался) "Материалы по достижимости с ограничениями в терминах формальных языков" это прям бомба! Лучшее что я находил на просторах русско и англоязычного интернета. Но полноценных лекций, конечно, не хватает.

**Comment by gsvgit** [comment]
@likern , день добрый. Структурированных видео, увы, нету. Неструктурированных тоже. К меня, по крайней мере. А дальше все зависит от того, чего на самом деле хочется. Если знаний в алгоритмах синтаксического анализа, то я бы рекомендовал Грюна (есть в материалах к курсу). А сели просто заиметь рабочий парсер sql, то просто взять antlr с его коллекцией парсеров (там куча разных диалектов поддержана).

**Comment by likern** [comment]
Жаль, но за конспекты спасибо. Скажем так, сейчас я читаю Crafting Interpreters. Но хотелось бы понимать к этому понимать теорию, те да алгоритмы синтаксического анализа. Чтобы как-то мыслить, делать какие-то выводы.

Язык будет собственный, оригинальный.
